language: ruby
branches:
  only:
  - travis-fixes
rvm:
- 2.0.0
install:
- bundle install
- rake bootstrap
script:
- rake deploy
env:
  global:
    secure: My0ofyyY57aqpfePTtDuow6MmoTipPxgTZ1MxJPHes0aFmO90x7PP4mjZds06Tz09Nq02msXUYuBFNNEfVPWLKYMQFgNt3qBCGZ+6mSMEHIauvkenQGZlBzkLYycWctGml9tRnIpbqJwv0xdrkTslVwDQU5IEJNZiTlJ2tYl8og=
