language: ruby
branches:
  only:
  - master
rvm:
- 2.1.3
install:
- gem install bundler
- bundle install
- rake bootstrap
script:
- git config credential.helper 'cache'
- echo "protocol=https\nhost=github.com\npassword=${GH_TOKEN}" | git credential approve
- bundle exec rake deploy
